version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    restart: unless-stopped
    network_mode: host
    ports:
    - 5672:5672

  random_number_generator:
    image: registry.gitlab.com/aivero/public/programming-exercise
    container_name: rand_gen
    restart: unless-stopped
    network_mode: host
    environment:
      RUST_LOG: debug
    depends_on:
      - rabbitmq